🩹 Remove "Success!" message
MarcusOtter/discord-needle pull request #90
Opened 2022-02-19 18:27 UTC by nchristopher

This pull request removes the "Success!" button sent when clicking on the **Archive Thread** button.

Normally, interactions must be responded to with a message. However, button interactions are unique; editing the original message counts as a response.

This is accomplished by simply removing the buttons from the original button when clicked.

2022-02-19 22:08 UTC, c43721 approved these changes
+1

2022-02-22 04:48 UTC, c43721 commented
@nchristopher I just realized, if a user decided to unarchive a thread, the buttons would be lost. I think this isn't the correct solution.

2022-02-22 04:49 UTC, c43721 requested changes
@MarcusOtter Needs discussion. Updating the original message would result in buttons being lost forever.

2022-02-22 04:58 UTC, nchristopher commented
I hadn't considered that. I think we can add a space to the original message, then immediately edit the message to remove it.

2022-02-22 05:02 UTC, nchristopher commented
Turns out you can edit a message with the same exact content.

@c43721 This should be fixed now.

2022-02-22 14:07 UTC, c43721 approved these changes

2022-03-05 23:10 UTC, MarcusOtter approved these changes
Thank you, works great! I added it for the people that have the `Archive after 1 hour of inactivity` archive-behavior too:

![image](https://user-images.githubusercontent.com/35617441/156902723-fccdc731-c117-4567-ad8d-bafd4d5390a2.png)

2022-03-05 23:10 UTC, merged